### PR TITLE
Added sqlite3 online backup routine

### PR DESCRIPTION
**Pull request by wilsonmeier**
Added the integrated sqlite3 online backup functionality and Test with Xamarin Studio.

Sorry for the code reformat :)

### CODE REVIEW

**Comment by wilsonmeier** [comment]
All relevant changes within existing files are enclosed in "#region Backup"

**Comment by oysteinkrog** [comment]
Sorry, I can't merge this when there are so many unrelated changes.

**Comment by wilsonmeier** [comment]
There you go

**Comment by oysteinkrog** [comment]
Hehe, this is still very messy, and it is too much work for me to review this, as I would have to sift through everything.
Please rebase this so that only the necessary lines are changed, if you have trouble with that you can also create a new PR/branch.

**Pull request closed without merging**
