### PR TITLE
Run and await task inside AsyncConnection.RunInTransactionAsync

### PR DESCRIPTION
**Pull request by tmarti**
Changes for improvement suggested in #209.
Additionally, fixed ProjectId of SQL.Net.Tests.OSX (was duplicated with respect to another project).

### CODE REVIEW

**Comment by oysteinkrog** [comment]
Hi, I finally took at look at this today (so sorry for the delay).
I had to do some minor fixups due to code changes, but disregarding that I suspect that this is actually not possible to do. The test fails with:
System.Threading.SynchronizationException: Object synchronization method was called from an unsynchronized block of code.
I investigated and found that this is because your new method does:
using (conn.Lock())
inside an async context/delegate.
The conn.lock() uses a monitor (a lock), which as you know is not allowed in async.
One could use an async lock instead (e.g. nito asyncex lock), but I'm not sure if it's a good idea to mix async and sync locking.

**Comment by tmarti** [comment]
Ok, from you POV this makes perfect sense.

An example is: what would happen if the RunInTransactionAsync method has to await (for task A) while holding the lock?. Meanwhile, another (not necessarily async) method B could be invoked which also needed the lock.

If just one thread is available, this means having Task A awaiting (for example some network operation) while holding the lock, and method B blocked trying to access the lock.

As method B is blocked (does not await), control never gets back to Task A. As Task A cannot resume, the lock will never be released, so method B awaits. DEADLOCK!

Sorry for not having seen this situation before. I'm rather new to C# and have little experience managing the "parallel" and at the same time "sequential" nature of Tasks.

Thanks a lot for your response :)

**Comment by oysteinkrog** [comment]
Yeah, so if I understand correctly, the scenario you describe is exactly why it's important _not_ to do "other" stuff inside the transaction scope, only DB stuff.
This is kind of a fundamental problem, I wonder if there is a good solution.
Since sqlite does not support async stuff at this level, any attempt at trying to add it is probably going to cause problems.

**Comment by tmarti** [comment]
You're right Sir.

So the situation I was describing in the issue as a need (and that the did
lead to the commit) seems something to be avoided.

Luckily, I was not using the mechanism by the moment.

(Me) Not knowing enough about: SQLite native library; the library wrapper;
specially, ways to circumvent the lock-Task limitation, caution is the best
tip here (we won't discover the wheel on a PR discussion).

Glad to understand that this can be a very tricky functionality to
implement :)

**Pull request closed without merging**
