### PR TITLE
Made the main library support .Net 4.0

### PR DESCRIPTION
**Pull request by Shiney**
Had to use older versions of the reflection API

### CODE REVIEW

**Comment by prasannavl** [comment]
You just went back in time. 

The proper way to do this, if it really has to be done would be to use `#ifdef`s.

**Comment by oysteinkrog** [comment]
Hmm, yeah I am really torn on this.
On the one hand it feels .. wrong .. to go backwards:p
But on the other hand this would only increase compatability, with no real downsides.
@prasannavl What do you think, considering the above?

**Comment by Shiney** [comment]
It seems to me that using #ifdefs is going against the spirit of it being a PCL, I think it would be good to think of it as supporting another platform just like we have to avoid System.Data as it is a PCL rather than a pure .NET dll.

**Comment by prasannavl** [comment]
The fact is these aren't directly compatible APIs when you switch to .NET 4.5. And if, for whatever reason we start making use of the 4.5 specific feature set later, all these APIs will have to be reversed again. That's the problem. 

So, I think a better approach is to do exactly what you did for GetCustomAttributes. ReflectionExtensions class should have a set of functions (for each of the changes you made), which internally uses #ifdefs, so that the current APIS are unaffected, should we drop 4.0 later. So the usage of #ifdefs are all constrained into one region, and concerns clearly separated. Going down a path which clearly could cause incompatible changes in the future isn't something I'd like walk into.

**Comment by oysteinkrog** [comment]
I'm sorry but I've decided not to accept this.
I don't want to maintain it :/

**Pull request closed without merging**
