### PR TITLE
Made default and collation attributes work better with attribute subtypes

### PR DESCRIPTION
**Pull request by Shiney**
Fixed the code that deals with the DefaultAttribute and the CollationAttribute to allow subtypes of them to be used, 

Also added some tests to demonstrate that it works and provide some motivation for why this is a useful feature.

### CODE REVIEW

**Comment by oysteinkrog** [comment]
Hi man, thanks for the recent fixes.
This looks a bit messy, is it ready for review?

**Comment by Shiney** [comment]
Hi I'm likely to be using it on a project soon and I want to fix some of
the problems before I use it in anger.

The code is ready for review but I'm just starting with git so the commits
are messy. I can clean them up first if you want.

**Comment by oysteinkrog** [comment]
I would appreciate that, I'm trying to keep things as clean as possible.

**Comment by Shiney** [comment]
I'm closing this one and have made another one.

**Pull request closed without merging**
