### PR TITLE
* add: sqlite online backup routine and unittest

### PR DESCRIPTION
**Pull request by wilsonmeier**
Added sqlite3 online backup routine

### CODE REVIEW

**Comment by oysteinkrog** [comment]
Hmm, this breaks some of the platforms (you did not implement it in all of them).
Do you know if these sqlite backup functions are supported across all the platforms?
If not we may have to make this functionality optional in some way.

**Comment by wilsonmeier** [comment]
You're right, i just implemented the platforms i can test with xamarin. I've now installed VS 2012 to implement the remaining platforms. The Backup functions are not supported by wp8 as the 3rd party library does not implement it. So i introduced a new interface ISQliteApiExt which inherits from ISQliteApi and moved the backup functions to it. Every platform supporting backup inherits from the new interface whereas wp8 uses the ISQliteApi. I don't have that much time so i hope this is an acceptable approach to you.

**Comment by oysteinkrog** [comment]
Yeah, that sounds like a nice solution.

**Comment by wilsonmeier** [comment]
Glad to here that. Do you plan to integrate this pull request into the next release?

**Comment by oysteinkrog** [comment]
I'm sorry about the delay, I will try to find time this weekend to look at this and hopefully get it merged.

**Comment by wilsonmeier** [comment]
Thx :)

**Pull request closed without merging**
