### PR TITLE
Cleanup TableMapping, abstract out ActiveInsertCommand, and facilitate TableMapping sharing between connections

### PR DESCRIPTION
**Pull request by prasannavl**
- Removed everything from TableMapping that makes its specific to SQLiteConnection
- Remove all unnecessary dependencies of TableMapping
- Create ActiveInsertCommand class that has everything in the Map that's specific to SQLiteConnection
- TableMapping is now lighter, reusable, and can now be shared between SQLiteConnections, increasing the performance multifold, if new connections are created often. 
- This also now facilitates a real ConnectionPool without reflecting all over again on types which similar connections have already mapped out.

### CODE REVIEW

**Comment by prasannavl** [comment]
PS: I apologize for not propagating the changes to the unit tests, if any. Tests were failing for whatever reason even in the original fork, and since my changes were something that could affect the tests, I didn't bother. But the addition of parameter to the constructor would be something that might have to be propagated.  I'd appreciate if someone else can do it. :)

Cheers.

**Comment by oysteinkrog** [comment]
I think this is a good idea, but I'm a bit worried about the additional ctor argument.
My primary concern is that the ctor's already have a lot of parameters, and I would prefer not to burden users with even _more_ concerns.
Can we preserve the existing ctor's (to preserve compatability)?
What do you think about making the default behavior more "easy to use", by having it use a static mapping manager of some kind?

**Comment by prasannavl** [comment]
Static mapping is what I initially thought about. Frankly, its also easier to implement. But the problem is that, TableMapping need not necessarily be the same as the mapping for the type. 

For example, one can have a connection where one may want to map differently, and/or tweak mappings extensively. This way, its cleaner, each connection gets it own mapping (which could very well simply be a reference to a static mapping). 

But we could workaround it, if compatibility is an absolute must. But making it settable property, with a default static mapping. But just didn't seem clean to me.

**Comment by prasannavl** [comment]
Also, regarding the easy to use, personally I think the Connection class shouldn't carry any more responsibility than it already has. I think, if we can implement a pool abstraction which shares the mapping, that would make a lot more sense. And since, ideally a normal use case will be moving away from using the Connection directly, and using the pool, that'll become a lot more simpler. I think an "easy-to-use" abstraction over this would make better sense, than adding more functionality to make this class easier to you.

**Comment by prasannavl** [comment]
Also, another viable option is to reduce the number of ctor parameters, and making into a ConfigurationOptions of somekind - So, even a single instance of options could be passed over to multiple connections. Thinking about it, I think that's a finer approach, since there are too many arguments now. But that still slashes down compatibility. 

What do you think?

**Comment by oysteinkrog** [comment]
Regarding the struct option; yes, I've had this thought as well.
I've bumped the major version to 3.0 now so we can probably do some breaking changes, but I still prefer to avoid them as much as possible, since I am pretty sure most of the users would prefer that as well.
Regarding the pool abstraction; why is multiple connections desirable in the first place? Due to multiple threads?

**Comment by prasannavl** [comment]
I think it should be a class more than struct. Since we'll end up having a couple of fields already, and if we want to add more in the future, it'd become a breaking change if we have to move to struct to a class. Sharing the instance will also not make sense if its a struct. 

And multiple connections - Concurrency. Readers don't lock on SQLite.

**Comment by prasannavl** [comment]
The version bump is convenient. We can map lookahead and plan this well. 
How about, 

ConfigOptions {
DateTimeOptions DateTimeOptions [Flags of DateTimeOptions.StoreAsTicks, DateTimeOptions.UseUtcRepresentations], 
IBlobSerializer Serializer,
TableMappings,
ExtraMappings,
Resolver,
Platform,
}

And then for platform, make a static SQLitePlatform.Init(), which autoloads the platform, and perhaps accepts a platform loader as an optional argument. So, need to go around passing the platform each time, once the platform is established. 

Infact, if the platform is not set, we could already try to determine it automatically without user input.

**Comment by oysteinkrog** [comment]
That looks good, I've also considered adding some types to help build the connection string.
I think most users are not aware of the fact that the connection string can contain many sqlite pragmas that are useful. Adding an API (possibly fluent) for configuring this would fit well with this.

**Comment by prasannavl** [comment]
Great. Let me know how you'd like to proceed. If you prefer merging this and then doing the initial bits on the configurations, I'll wait. Or I'll add on another commit with the configuration options to go.

**Comment by oysteinkrog** [comment]
Hmm, this did indeed break one of the NotNullAttribute tests.

**Comment by prasannavl** [comment]
Yes, I had glanced across it. It was due to the extensive changes in the data structures however, and not a test failure. But on a quick glance, I wasn't sure how to restructure that specific test though. Since a few members directly weren't accessible as a consequence of the changes.

**Pull request merged**
