### PR TITLE
Changes needed to compile in VS2015 w/ latest Xamarin

### PR DESCRIPTION
**Pull request by tofutim**
Addresses my issue in #239 - This is a fresh install of VS2015 with the latest Xamarin bits. Changes the hint path to ..\.. from C:\WORK\REPOS in Tests.Generic, updates the Android framework to 6, re-install PCLStorage in iOS, updated TestFramework version 14 for WinRT

### CODE REVIEW

**Comment by tofutim** [comment]
I'm sad that AppVeyor fails - is it because of multiple slns? Doesn't yaml specify the right sln?

**Comment by tofutim** [comment]
Fix for #242 in this PR. After removing the two bad references in OSS, everything is compiling in appveyor but it dies because of failed tests due to

System.DllNotFoundException : Unable to load DLL 'sqlite3': The specified module could not be found. (Exception from HRESULT: 0x8007007E)

**Comment by tofutim** [comment]
Ok, I see the problem here, all the Generic Tests fail because sqlite3 is not present in the test folder. All the Win32 pass. https://ci.appveyor.com/project/oysteinkrog/sqlite-net-pcl/build/1.0.217/tests

Solutions: 
1. remove Generic Tests from OSS
2. ignore Generic Tests
3. add sqlite3.dll

**Comment by tofutim** [comment]
Never worked this hard for a PR before. ;P  Ncrunch successfully runs the Generic Tests (minus the ones that don't work like Stress) when sqlite3.dll is added. However, appveyor now complains that

System.BadImageFormatException : An attempt was made to load a program with an incorrect format. (Exception from HRESULT: 0x8007000B)

**Comment by tofutim** [comment]
Maybe Generic wants x64 version?

**Comment by tofutim** [comment]
Swapping in the x64 sqlite3.dll worked - it is now just failing tests which are ignored in Win32. Now just to figure out how to ignore those tests.

SQLite.Net.Tests.BlobDelegateTest.CallsOnUnsupportedTypes
SQLite.Net.Tests.Generic.dll 20 ms
SQLite.Net.Tests.AsyncTests.StressAsync
SQLite.Net.Tests.Win32.dll 8 sec 23 ms
SQLite.Net.Tests.AsyncTests.StressAsync
SQLite.Net.Tests.Generic.dll 9 sec 46 ms
SQLite.Net.Tests.BlobDelegateTest.CallsOnUnsupportedTypes
SQLite.Net.Tests.Win32.dll 63 ms

**Comment by tofutim** [comment]
Not sure why but the Assert.Ignore is not being tripped in the Generic Tests, although it is in the Windows one.
```
Tests run: 332, Errors: 0, Failures: 4, Inconclusive: 0, Time: 39.9826234 seconds
  Not run: 4, Invalid: 0, Ignored: 4, Skipped: 0
 
Errors and Failures:
1) Test Failure : SQLite.Net.Tests.AsyncTests.StressAsync
     Expected: 0
  But was:  18
 
at SQLite.Net.Tests.AsyncTests.<StressAsync>d__32.MoveNext() in c:\projects\sqlite-net-pcl\tests\AsyncTests.cs:line 217
at NUnit.Framework.AsyncInvocationRegion.AsyncTaskInvocationRegion.WaitForPendingOperationsToComplete(Object invocationResult)
at NUnit.Core.NUnitAsyncTestMethod.RunTestMethod()
 
2) Test Failure : SQLite.Net.Tests.BlobDelegateTest.CallsOnUnsupportedTypes
     Expected: collection containing <System.DateTimeOffset>
  But was:  <empty>
 
at SQLite.Net.Tests.BlobDelegateTest.CallsOnUnsupportedTypes() in c:\projects\sqlite-net-pcl\tests\BlobSerializationTest.cs:line 307
 
3) Test Failure : SQLite.Net.Tests.AsyncTests.StressAsync
     Expected: 0
  But was:  17
 
at SQLite.Net.Tests.AsyncTests.<StressAsync>d__32.MoveNext() in c:\projects\sqlite-net-pcl\tests\AsyncTests.cs:line 217
at NUnit.Framework.AsyncInvocationRegion.AsyncTaskInvocationRegion.WaitForPendingOperationsToComplete(Object invocationResult)
at NUnit.Core.NUnitAsyncTestMethod.RunTestMethod()
 
4) Test Failure : SQLite.Net.Tests.BlobDelegateTest.CallsOnUnsupportedTypes
     Expected: collection containing <System.DateTimeOffset>
  But was:  <empty>
 
at SQLite.Net.Tests.BlobDelegateTest.CallsOnUnsupportedTypes() in c:\projects\sqlite-net-pcl\tests\BlobSerializationTest.cs:line 307
 
 
Tests Not Run:
1) Ignored : SQLite.Net.Tests.BlobDelegateTest.BlobSerializationTest.VerifyTableCreationSucceedsWithSupportedSerializer
   Serialize does not support this data type
   at NUnit.Framework.Assert.Ignore(String message, Object[] args)
   at SQLite.Net.Tests.BlobSerializationTest.VerifyTableCreationSucceedsWithSupportedSerializer() in c:\projects\sqlite-net-pcl\tests\BlobSerializationTest.cs:line 160
 
2) Ignored : SQLite.Net.Tests.ConnectionTrackingTest.CreateThem
   This test class/file was not included in the original project and is broken
3) Ignored : SQLite.Net.Tests.BlobDelegateTest.BlobSerializationTest.VerifyTableCreationSucceedsWithSupportedSerializer
   Serialize does not support this data type
   at NUnit.Framework.Assert.Ignore(String message, Object[] args)
   at SQLite.Net.Tests.BlobSerializationTest.VerifyTableCreationSucceedsWithSupportedSerializer() in c:\projects\sqlite-net-pcl\tests\BlobSerializationTest.cs:line 160
 
4) Ignored : SQLite.Net.Tests.ConnectionTrackingTest.CreateThem
   This test class/file was not included in the original project and is broken
 
Command exited with code 4
````

**Comment by tofutim** [comment]
In https://github.com/oysteinkrog/SQLite.Net-PCL/issues/196 the StressAsync and CallsOnUnsupportedTypes is said to be buggy.

**Comment by tofutim** [comment]
oops, hold on that last commit, newtonsoft didn't get picked up

**Comment by tofutim** [comment]
Only the stress test fails now, #243 is resolved

**Comment by tofutim** [comment]
@oysteinkrog  let me know if you need these changes split out into separate PRs, don't think I can resolve #244 now, but appveyor is working properly now

**Comment by oysteinkrog** [comment]
The appveyor build has never actually worked :/
Thank you so much for looking at it.
I will look more closely at your changes and merge later this week (probably on Friday as I will have some free time).

**Comment by tofutim** [comment]
it is in my notes, but the major appveyor problem was that the yml file had
to be lower case - hard to diagnose!

**Pull request closed without merging**
