### PR TITLE
Add NuGet auto-restore build targets

### PR DESCRIPTION
**Pull request by prasannavl**
Referencing issue https://github.com/oysteinkrog/SQLite.Net-PCL/issues/152

### CODE REVIEW

**Comment by oysteinkrog** [comment]
Fe should not use the old-style restore (msbuild-based) as it has been deprecated.
The new workflow is to have the VS nuget extension handle it (or use nuget.exe when build outside VS).

**Comment by prasannavl** [comment]
Hi. Yes, that's true. But VS wasn't automatically restoring. So, had to manually restore for it to work. Anyway, the point being auto restore is unaffected. This is just an additional step that takes care of it, if in case it wasn't restored.

**Comment by oysteinkrog** [comment]
Well, I remove it from the project files on purpose as it's not needed any longer, it just slows down the build.
Were you able to find out why it did not restore for you?
I am a bit reluctant to include it "just in case" (the eternal fight against cargo-culting), but I will if the current setup legitimately causes problems.

**Comment by oysteinkrog** [comment]
I would also like to add that the _official_ nuget docs recommends using the new system: 
"Automatic Package Restore is the NuGet team's recommended approach to Package Restore within Visual Studio..."
https://docs.nuget.org/consume/package-restore
https://docs.nuget.org/Consume/Package-Restore/Migrating-to-Automatic-Package-Restore

**Comment by prasannavl** [comment]
Makes sense. :)

I wasn't able to reproduce it with fresh clones. I'm not quite sure why it wouldn't restore. Anyway, I guess I lost the window to figure out why my old repo didn't auto-restore as soon as you made the changes that involved the restore. So, I guess, as you suggested, its best to leave this commit out.  Closing this.

**Comment by prasannavl** [comment]
Ok, this is interesting. Was just fixing up another commit without this, and for fresh clones of this repo, VS is automatically adding these anyway during the build. My tooling definitely does have the newer restore mechanism turned on.

**Pull request closed without merging**
