### PR TITLE
Added support for IoC and resolving interfaces during object creation

### PR DESCRIPTION
**Pull request by ravensorb**
Added support for a Contract Resolver.  This can be used by any DI/IOC container.

### CODE REVIEW

**Comment by oysteinkrog** [comment]
I am currently traveling and do not have time/access to look at this, but I will be home in a few days and will look at it then.

**Comment by ravensorb** [comment]
No problem -- let me know if you want to talk over the implementation, or have suggestions on a better way to implement it.

**Comment by oysteinkrog** [comment]
Hmm, this is a nice idea and I think this functionality is something many could benefit from.
I am a bit worried about changing all the generic constraints from new() to class but I don't see any way around that.
You have some unrelated changes, e.g. in the ios project, please amend your commit to remove those.
Is there a reason why you added a new test project?

**Comment by ravensorb** [comment]
Interesting -- I didn't make that change intentionally.  I'll revert it.

Note:  I just added 1 more commit that cleaned a few things up and added full comments to the IContractResolver and ContractResolver class.

As for the separate unit test project -- I did that just so I would not impact the existing ones in any way. My way of verifying 100% that the library was still completely backwards compatible.  We can merge them if you want.

**Comment by ravensorb** [comment]
Is there anything else I can do to help with this or are we ok to commit this to the main branch?

**Comment by oysteinkrog** [comment]
Sorry about delaying this, I will take a new look during this weekend and hopefully get it merged.

**Comment by oysteinkrog** [comment]
Finally got this merged, sorry again about the delay.

**Comment by oysteinkrog** [comment]
While looking close at this I found that the resolver is used even for the internal ColumnInfo type, is this intentionally?
I really don't like how this requires the IoC framework to instantiate what is basically an unknown and internal sqlite.net type.

**Comment by ravensorb** [comment]
Hmm, excellent point.  There really should not be a need for resolving types at that point.

Sent from my Windows Phone
________________________________

**Comment by ravensorb** [comment]
Question, I am testing beta4 on Windows Phone and am getting the following crash

An exception of type 'System.TypeLoadException' occurred in SQLite.Net.DLL but was not handled in user code

Additional information: Could not find Windows Runtime type 'Sqlite.Sqlite3'

Are we missing a dependency?

**Pull request closed without merging**
